# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcserver/grpcserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgrpcserver/grpcserver.proto\x12\ngrpcserver\"\x0e\n\x0cNoneResponse\"\x1a\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x1a\n\x07Timeout\x12\x0f\n\x07seconds\x18\x01 \x01(\x01\x32\x82\x01\n\nGRPCServer\x12<\n\x0bPushMessage\x12\x13.grpcserver.Message\x1a\x18.grpcserver.NoneResponse\x12\x36\n\nPopMessage\x12\x13.grpcserver.Timeout\x1a\x13.grpcserver.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcserver.grpcserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NONERESPONSE']._serialized_start=43
  _globals['_NONERESPONSE']._serialized_end=57
  _globals['_MESSAGE']._serialized_start=59
  _globals['_MESSAGE']._serialized_end=85
  _globals['_TIMEOUT']._serialized_start=87
  _globals['_TIMEOUT']._serialized_end=113
  _globals['_GRPCSERVER']._serialized_start=116
  _globals['_GRPCSERVER']._serialized_end=246
# @@protoc_insertion_point(module_scope)
