# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10grpcserver.proto\x12\ngrpcserver\"\x06\n\x04Void\"\x1a\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"!\n\x0e\x42rowserRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\"\n\x0f\x42rowserResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x19\n\tQueueSize\x12\x0c\n\x04size\x18\x01 \x01(\r\"\x1a\n\x07Timeout\x12\x0f\n\x07seconds\x18\x01 \x01(\x01\x32\xdc\x03\n\nGRPCServer\x12\x35\n\x0cpush_message\x12\x13.grpcserver.Message\x1a\x10.grpcserver.Void\x12\x37\n\x0bpop_message\x12\x13.grpcserver.Timeout\x1a\x13.grpcserver.Message\x12\x44\n\x14push_browser_request\x12\x1a.grpcserver.BrowserRequest\x1a\x10.grpcserver.Void\x12\x46\n\x13pop_browser_request\x12\x13.grpcserver.Timeout\x1a\x1a.grpcserver.BrowserRequest\x12>\n\x13len_browser_request\x12\x10.grpcserver.Void\x1a\x15.grpcserver.QueueSize\x12\x46\n\x15push_browser_response\x12\x1b.grpcserver.BrowserResponse\x1a\x10.grpcserver.Void\x12H\n\x14pop_browser_response\x12\x13.grpcserver.Timeout\x1a\x1b.grpcserver.BrowserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOID']._serialized_start=32
  _globals['_VOID']._serialized_end=38
  _globals['_MESSAGE']._serialized_start=40
  _globals['_MESSAGE']._serialized_end=66
  _globals['_BROWSERREQUEST']._serialized_start=68
  _globals['_BROWSERREQUEST']._serialized_end=101
  _globals['_BROWSERRESPONSE']._serialized_start=103
  _globals['_BROWSERRESPONSE']._serialized_end=137
  _globals['_QUEUESIZE']._serialized_start=139
  _globals['_QUEUESIZE']._serialized_end=164
  _globals['_TIMEOUT']._serialized_start=166
  _globals['_TIMEOUT']._serialized_end=192
  _globals['_GRPCSERVER']._serialized_start=195
  _globals['_GRPCSERVER']._serialized_end=671
# @@protoc_insertion_point(module_scope)
