from majsoulrpa.assets import TEMPLATES_DIR

LOGIN_1_SETTINGS_PATH = TEMPLATES_DIR / "login" / "login-1.toml"
LOGIN_1_TEMPLATE_PATH = TEMPLATES_DIR / "login" / "login-1.png"
YOSTAR_LOGO_SETTINGS_PATH = TEMPLATES_DIR / "login" / "yostar-logo.toml"
YOSTAR_LOGO_TEMPLATE_PATH = TEMPLATES_DIR / "login" / "yostar-logo.png"

MAINTENANCE_OK_SETTINGS_PATH = TEMPLATES_DIR / "login" / "maintenance-ok.toml"
MAINTENANCE_OK_TEMPLATE_PATH = TEMPLATES_DIR / "login" / "maintenance-ok.png"

__all__ = [
    "LOGIN_1_SETTINGS_PATH",
    "LOGIN_1_TEMPLATE_PATH",
    "MAINTENANCE_OK_SETTINGS_PATH",
    "MAINTENANCE_OK_TEMPLATE_PATH",
    "YOSTAR_LOGO_SETTINGS_PATH",
    "YOSTAR_LOGO_TEMPLATE_PATH",
]
