from majsoulrpa.assets import TEMPLATES_DIR

SUMMON_SETTINGS_PATH = TEMPLATES_DIR / "home" / "summon.toml"
SUMMON_TEMPLATE_PATH = TEMPLATES_DIR / "home" / "summon.png"

JADE_SETTINGS_PATH = TEMPLATES_DIR / "home" / "jade.toml"
JADE_TEMPLATE_PATH = TEMPLATES_DIR / "home" / "jade.png"
NOTIFICATION_CLOSE_SETTINGS_PATH = (
    TEMPLATES_DIR / "home" / "notification-close.toml"
)
NOTIFICATION_CLOSE_TEMPLATE_PATH = (
    TEMPLATES_DIR / "home" / "notification-close.png"
)
EVENT_CLOSE_SETTINGS_PATH = TEMPLATES_DIR / "home" / "event-close.toml"
EVENT_CLOSE_TEMPLATE_PATH = TEMPLATES_DIR / "home" / "event-close.png"
MAIL_CLOSE_SETTINGS_PATH = TEMPLATES_DIR / "home" / "mail-close.toml"
MAIL_CLOSE_TEMPLATE_PATH = TEMPLATES_DIR / "home" / "mail-close.png"
REWARDS_SIGN_IN_SETTINGS_PATH = TEMPLATES_DIR / "home" / "rewards-sign-in.toml"
REWARDS_SIGN_IN_TEMPLATE_PATH = TEMPLATES_DIR / "home" / "rewards-sign-in.png"
REWARDS_CONFIRM_SETTINGS_PATH = TEMPLATES_DIR / "home" / "rewards-confirm.toml"
REWARDS_CONFIRM_TEMPLATE_PATH = TEMPLATES_DIR / "home" / "rewards-confirm.png"

TOURNAMENT_MATCH_SETTINGS_PATH = (
    TEMPLATES_DIR / "home" / "tournament-match.toml"
)
TOURNAMENT_MATCH_TEMPLATE_PATH = (
    TEMPLATES_DIR / "home" / "tournament-match.png"
)
FRIENDLY_MATCH_SETTINGS_PATH = TEMPLATES_DIR / "home" / "friendly-match.toml"
FRIENDLY_MATCH_TEMPLATE_PATH = TEMPLATES_DIR / "home" / "friendly-match.png"

CREATE_ROOM_SETTINGS_PATH = TEMPLATES_DIR / "home" / "create-room.toml"
CREATE_ROOM_TEMPLATE_PATH = TEMPLATES_DIR / "home" / "create-room.png"

__all__ = [
    "CREATE_ROOM_SETTINGS_PATH",
    "CREATE_ROOM_TEMPLATE_PATH",
    "EVENT_CLOSE_SETTINGS_PATH",
    "EVENT_CLOSE_TEMPLATE_PATH",
    "FRIENDLY_MATCH_SETTINGS_PATH",
    "FRIENDLY_MATCH_TEMPLATE_PATH",
    "JADE_SETTINGS_PATH",
    "JADE_TEMPLATE_PATH",
    "MAIL_CLOSE_SETTINGS_PATH",
    "MAIL_CLOSE_TEMPLATE_PATH",
    "NOTIFICATION_CLOSE_SETTINGS_PATH",
    "NOTIFICATION_CLOSE_TEMPLATE_PATH",
    "REWARDS_CONFIRM_SETTINGS_PATH",
    "REWARDS_CONFIRM_TEMPLATE_PATH",
    "REWARDS_SIGN_IN_SETTINGS_PATH",
    "REWARDS_SIGN_IN_TEMPLATE_PATH",
    "SUMMON_SETTINGS_PATH",
    "SUMMON_TEMPLATE_PATH",
    "TOURNAMENT_MATCH_SETTINGS_PATH",
    "TOURNAMENT_MATCH_TEMPLATE_PATH",
]
