from majsoulrpa.assets import TEMPLATES_DIR

SEAT_INDICATOR_SETTINGS_PATH = TEMPLATES_DIR / "match" / "seat-indicator.toml"
SEAT_INDICATOR_TEMPLATE_PATHS = tuple(
    TEMPLATES_DIR / "match" / f"seat-indicator-{index}.png"
    for index in range(4)
)

BUTTON_AREA_SETTINGS_PATH = TEMPLATES_DIR / "match" / "button-area.toml"
CHI_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "chi.png"
PENG_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "peng.png"
GANG_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "gang.png"
LIQI_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "liqi.png"
LIUJU_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "liuju.png"
BABEI_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "babei.png"
SKIP_SETTINGS_PATH = TEMPLATES_DIR / "match" / "skip.toml"
SKIP_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "skip.png"

HULE_CONFIRM_SETTINGS_PATH = TEMPLATES_DIR / "match" / "hule-confirm.toml"
HULE_CONFIRM_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "hule-confirm.png"
LIUJU_CONFIRM_SETTINGS_PATH = TEMPLATES_DIR / "match" / "liuju-confirm.toml"
LIUJU_CONFIRM_TEMPLATE_PATH = TEMPLATES_DIR / "match" / "liuju-confirm.png"
ROUND_RESULT_CONFIRM_SETTINGS_PATH = (
    TEMPLATES_DIR / "match" / "round-result-confirm.toml"
)
ROUND_RESULT_CONFIRM_TEMPLATE_PATH = (
    TEMPLATES_DIR / "match" / "round-result-confirm.png"
)
MATCH_RESULT_CONFIRM_SETTINGS_PATH = (
    TEMPLATES_DIR / "match" / "match-result-confirm.toml"
)
MATCH_RESULT_CONFIRM_TEMPLATE_PATH = (
    TEMPLATES_DIR / "match" / "match-result-confirm.png"
)

__all__ = [
    "BABEI_TEMPLATE_PATH",
    "BUTTON_AREA_SETTINGS_PATH",
    "CHI_TEMPLATE_PATH",
    "GANG_TEMPLATE_PATH",
    "HULE_CONFIRM_SETTINGS_PATH",
    "HULE_CONFIRM_TEMPLATE_PATH",
    "LIQI_TEMPLATE_PATH",
    "LIUJU_CONFIRM_SETTINGS_PATH",
    "LIUJU_CONFIRM_TEMPLATE_PATH",
    "LIUJU_TEMPLATE_PATH",
    "MATCH_RESULT_CONFIRM_SETTINGS_PATH",
    "MATCH_RESULT_CONFIRM_TEMPLATE_PATH",
    "PENG_TEMPLATE_PATH",
    "ROUND_RESULT_CONFIRM_SETTINGS_PATH",
    "ROUND_RESULT_CONFIRM_TEMPLATE_PATH",
    "SEAT_INDICATOR_SETTINGS_PATH",
    "SEAT_INDICATOR_TEMPLATE_PATHS",
    "SKIP_SETTINGS_PATH",
    "SKIP_TEMPLATE_PATH",
]
