# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from majsoulrpa._impl.grpcserver import grpcserver_pb2 as grpcserver_dot_grpcserver__pb2


class GRPCServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushMessage = channel.unary_unary(
                '/grpcserver.GRPCServer/PushMessage',
                request_serializer=grpcserver_dot_grpcserver__pb2.Message.SerializeToString,
                response_deserializer=grpcserver_dot_grpcserver__pb2.NoneResponse.FromString,
                )
        self.PopMessage = channel.unary_unary(
                '/grpcserver.GRPCServer/PopMessage',
                request_serializer=grpcserver_dot_grpcserver__pb2.Timeout.SerializeToString,
                response_deserializer=grpcserver_dot_grpcserver__pb2.Message.FromString,
                )


class GRPCServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PopMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMessage,
                    request_deserializer=grpcserver_dot_grpcserver__pb2.Message.FromString,
                    response_serializer=grpcserver_dot_grpcserver__pb2.NoneResponse.SerializeToString,
            ),
            'PopMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PopMessage,
                    request_deserializer=grpcserver_dot_grpcserver__pb2.Timeout.FromString,
                    response_serializer=grpcserver_dot_grpcserver__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcserver.GRPCServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcserver.GRPCServer/PushMessage',
            grpcserver_dot_grpcserver__pb2.Message.SerializeToString,
            grpcserver_dot_grpcserver__pb2.NoneResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PopMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcserver.GRPCServer/PopMessage',
            grpcserver_dot_grpcserver__pb2.Timeout.SerializeToString,
            grpcserver_dot_grpcserver__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
